name: Build image

on:
  schedule:
    - cron: '30 20 * * *'  # 8:30pm everyday
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README*'
      - '*.md'
      - '*.png'
      - '*.txt'
  push:
    branches:
      - main
    paths-ignore:
      - 'README*'
      - '*.md'
      - '*.png'
      - '*.txt'
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor:
            latest=false
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=sha256-

      - name: Extract Docker PR tag
        if: github.event_name == 'pull_request'
        id: meta_pr
        uses: docker/metadata-action@v4
        with:
          images:
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor:
            latest=false
          tags:
            type=ref,event=pr

      - name: Extract Docker date tag
        if: github.event_name == 'schedule'
        id: meta_date
        uses: docker/metadata-action@v4
        with:
          images:
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor:
            latest=true
          tags:
            type=schedule,prefix=nightly-,pattern={{date 'YYYYMMDD'}}

      - name: Extract Docker major version tag
        if:
          github.event_name != 'pull_request'
        id: meta_version
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.meta_pr.outputs.tags }}
            ${{ steps.meta_date.outputs.tags }}
            ${{ steps.meta_version.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false

      - name: Push to container registries
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          tags: ${{ steps.build_image.outputs.tags }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
